### DISCUSSION TITLE
Tight Coupling: Improvements to UI

### DISCUSSION THREAD

**Discussion by albeanth** [terrapower/armi#1245] [Ideas]
This moves #1094 to here. TP and USNC have a joint interest in moving the development of the tight coupling user-interface forward. This discussion board serves to document 1) what we'd like to accomplish, 2) how we'd like to do it, and 3) the development tasks to accomplish the UI improvements. 

------------------

### Desired Outcomes
Moving parameters for convergence off of the interfaces and instead interact with the ARMI composites (via the database) directly. This new interface would look like
```yaml
tightCouplingSettings:
    core:
        parameter: keff
        convergence: 1e-4
    blocks:
        parameter: power
        convergence: 1e-3
```
This would:
1. remove the ambiguity of parameters "belonging" to interfaces, since they really only "belong" to the ARMI data model.
2. be a cleaner/clearer approach to managing convergence on different composite levels (e.g., converging on assembly-power vs block power, peak assembly temperature vs block temperature, multiple temperatures [clad, fuel, coolant, etc], etc...)
3. (USNC request) To switch between relative and absolute convergence criteria or have both at the same time so we can move on when either one is met (like moose)
```yaml
tightCouplingSettings:
    foo:
        parameter: bar
        # Stops iteration when either one is met
        abs_tolerance: 1e-4
        rel_tolerance: 1e-5 
   baz:
        parameter: qux
        abs_tolerance: 1e-4
```
5. (USNC request) More than one parameters per ~interface~ composite to evaluate the convergence
