### ISSUE TITLE
Tight coupling: interpretability of convergence norms 

### ISSUE THREAD

**Issue by albeanth** [terrapower/armi#1093]
This is also related to #1089. 

It was brought up in an offline conversation that it would be worth considering associating units to convergence criteria for parameters.

As of now, interface convergence can be measured in a normalized fashion. For example, keff and power can both be set to have convergence criteria of 1e-4. However, this does not necessarily mean that power is being converged to 1e-4 W. Rather, it is based on how the developer sets up the interpretation of measuring convergence. For example, in PR https://github.com/terrapower/armi/pull/1033 the block wise power for a given assembly is first normalized by the total power of its parent assembly. This normalized block power is then used to measure the L2-norm and ultimately, the convergence of the power distribution in the core. Though this sort of ambiguity may be unclear at first, in my experience, this sort of "under-the-hood" scaling/normalization is fairly commonplace. An advantage is that it gives equal weight to each power-producing assembly when determining if the overall power distribution is converged. 

Though this sort of scaling/normalization would ideally be detailed in the documentation, there may be a desire to improve the user interpretability of convergence criteria. One idea would be to retain the units (when applicable) when setting convergence in the `tightCouplingSettings`. So for the case of blockwise power, this would eliminate the need for scaling and the convergence would be set in units of Watts.

```yaml
# old/current approach
tightCouplingSettings:
    blocks:
        parameter: power
        convergence: 1e-4   # assembly power is scaled/normalized under-the-hood to achieve this

```
```yaml
# new proposed approach
tightCouplingSettings:
    blocks:
        parameter: power
        convergence: 100.0  # units of W. 
```
However, this new approach would not give equal weighting to all power-producing assemblies and could possibly be problematic in the long run. For example, if there are power-producing assemblies that are significantly lower power relative to higher power assemblies (e.g., periphery/poisoned vs central assemblies), the convergence of the power distribution in those low-power assemblies may actually never be considered as the error would be dominated by the higher power assemblies. One could argue that this is fine as one may only really care about the highest power producing assemblies. While valid, this approach is arguably less mathematically rigorous when considering the power distribution of the whole core as now you are only really sure that the highest power-producing assemblies are converged (while the low power assemblies may not be). 

I welcome other thoughts/concerns/questions!
