### ISSUE TITLE
Provide version-validating helper function

### ISSUE THREAD

**Issue by john-science** [terrapower/armi#1095]
In [this discussion](https://github.com/terrapower/armi/discussions/1066) @drewj-usnctech and I discussed the need for a simple helper function that could validate and match a version number.  For instance, it would need to be able to validate these cases:

* `1.2.3` meets `1.2.3`
* `1.2.3` does NOT meet `1.2.4`
* `1.2` meets `1.2.3`
* `1.3` does NOT meet `1.2.3`

The goal of this function is to provide a standard way for developer's plugins to check versions in settings files. Users could add a `Setting` for the version of their app, and then add a `SettingValidator` which would use this helper function to match the version.

**Comment by drewj-usnctech** [comment]
Thanks @john-science! Is the intent still to have these "metadata" settings in the `metadata` block in the settings input file? Or would they reside in the main body of the input? To put it another way, are we looking for
```yaml
metadata:
  version: uncontrolled  # armi version
  myApp : 4.2  # primary app version
  myTransportKernel: 1.2.3
settings:
  neutronicsKernel: myTransportKernel
```
vs.
```yaml
metadata:
  version: uncontrolled  # armi version
settings:
  myAppVersion: 4.2
  myTransportKernelVersion: 1.2.3
  neutronicsKernel: myTransportKernel
```

My preference would be for the former: versions in the `metadata`. But I know much of the plugin interface is focused on adding content to the `settings` section

**Comment by john-science** [comment]
I have a branch open for this helper method, Drew: https://github.com/terrapower/armi/commit/8f55cccea3f52b0616b3e6b09ce9f9f7ba737168

I am standing here looking at this dubious `metadata` section, and while I think the first option you have looks better:

```yaml
metadata:
  version: uncontrolled  # armi version
  myApp : 4.2  # primary app version
```

I'd like to support that for you, but it looks to be quite a large change. Where your second option is free:

```yaml
settings:
  myAppVersion: 4.2
```

Let me look at this a little longer.  I'd like to support the better option. But it appears we have no tooling build around the `metadata` section at all; it is just for this one `Setting`.  I don't like that that, but I'm thinking "perfect is the enemy of better.  

Let me keep poking around.
