### ISSUE TITLE
Incorrect pitch for tips up sub-block pin grid

### ISSUE THREAD

**Issue by drewj-usnctech** [terrapower/armi#1284]
In the same vein of #1278, the pin pitch seems to be off. The following grid definitions
```yaml
  pins:
    lattice pitch:
      x: 1.2
      y: 1.2
    geom: hex_corners_up
    lattice map: |
      - - O F F
       - F F F F
        F F F F F
         F F F F
          F F F
    # geom: hex
    # lattice map: |
    #   - F
    #    F F
    #   F F F
    #    F F
    #   F F F
    #    F F
    #   F F F
    #    F F
    #     F 
```
produce two different pitches. For the normal "flats up" hexagon, the pitch is correct: `b.spatialGrid.pitch=1.2`. But for the "tips up" grid, the pitch is off: `b.spatialGrid.pitch=1.0392304845413265` using
```python
import armi
armi.configure()
o = armi.init(fName="sample.yaml")
b = o.r.core[0][0]
g = b.spatialGrid
print(f"{b.spatialGrid.pitch=}")
```

My current workaround is to look at the `_unitSteps` attribute, which feels not ideal (using private attribute) 
```python
>>> b.spatialGrid._unitSteps
array([[ 0.6       , -0.6       ,  0.        ],
       [ 1.03923048,  1.03923048,  0.        ],
       [ 0.        ,  0.        ,  0.        ]])
>>> realPitch = b.spatialGrid._unitSteps[0,0] * 2
```
If I understand these right, the `_unitSteps[0, 0]` is the change in x for changing ring. So each new ring nets us a full new x-site, since they're all neighbors.
