### ISSUE TITLE
Support specifying depletion schedule with burnup (MWd/kgHM)

### ISSUE THREAD

**Issue by drewj-usnctech** [terrapower/armi#1364]
An alternative time schedule for depletion that is commonly used in reactor analysis is burnup in units of (typically) power * time / mass. Common variants are MWd/kgHM or GWd/tHM (same units if you assume metric tonne = 1000 kg). The heavy metal mass is often taken as the initial loading, so you may see a MWd/kgHMi just to be more clear as heavy metal mass can change through operation.

This ticket proposes allowing specifying a depletion schedule with `step burnup` or `cumulative burnup` units, mirroring the `step days` and `cumulative days` supported in the `cycles` arrays. An example input could look like
```yaml
settings:
  power: 1000000000 # 1 GW power
  nCycles: 2
  cycles:
    - name: A
      step burnup: [0.5, 0.5, 1, 2]
    - name: B
      cumulative burnup: [5, 10, 15 ,20]
```
wherein cycle `A` would deplete to 0.5, 1, 2, and 4 MWd/kgHM, and cycle `B` would deplete out to 5, 10, 15, and 20 MWd/kgHM.

It makes sense to disallow including burnup and day values in the same input, as the following would make no sense
```yaml
...
  cycles:
    - name: A
      step burnup: [0.5, 0.5, 1, 2]
      step days: [1, 2, 3, 4]
```

The same power fraction and availability factors fields should still be supported as if the schedule had been specified with days.

Given the total reactor power (known from settings file) and the heavy metal mass of the reactor (through `Reactor.getHMMass()`), it is possible to convert burnup steps to day steps, and provide the day stepping that ARMI uses internally.
