### ISSUE TITLE
Group specifications in cross section control setting are weird

### ISSUE THREAD

**Issue by keckler** [terrapower/armi#1710]
A typical example of using the `crossSectionControl` setting might look something like this:
```yaml
  crossSectionControl:
    GA:
      geometry: 0D
      fluxFileLocation: \\some\location
    LA:
      geometry: 1D cylinder
      validBlockTypes:
        - control
      blockRepresentation: ComponentAverage1DCylinder
      driverID: AA
      numExternalRings: 2
      mergeIntoClad:
        - gap
      meshSubdivisionsPerCm: 1.0
      xsMaxAtomNumber: 10
      minDriverDensity: 1e-8
      xsPriority: 1
```

Is it odd that XS groups in this setting are referred to by their type+burnup group (i.e. `GA` as compared to just `G`)? Here are a few potential points of confusion:
* The user might look through their blueprints and see that XS type `GA` is not defined for any blocks, for instance. This is confusing.
* This would seem to preclude 2-digit groups (see #1709 ) from being correctly handled. 
* It might make one think that the setting is referring to only the first burnup group of a given XS type, in which case the later burnup groups of that type would fall back to the default.
* Is the `driverID: AA` referring to the first burnup group of XS type `A`, or generically all of group `A`, or the 2-digit group `AA`? Is this driver group updated with burnup somehow?

It doesn't help that the `crossSectionControl` setting is hardly mentioned in the user docs.

I would suggest clarifying these few points, primarily by adding thorough documentation of the `crossSectionControl` setting, but also potentially by updating the way XS groups are specified within the setting itself.
