### ISSUE TITLE
yaml anchors in list input for blueprint

### ISSUE THREAD

**Issue by veeshy** [terrapower/armi#223]
I want to repeat an anchored list to build up a larger pattern, particularly to build up some axial detail. Is something like this possible (now or with some work) in the input?

```
assemblies:
    heights: &heights
        - 10
        - 10
    fuel:
        height:
              - *heights
              - *heights
              - *heights
```

Or perhaps an alt question here is, most efficient way to model axial details? I think I'm looking for an axial lattice now that I think about it.

An example: a fuel pellet needing 3 axial layers to get sufficient detail:

```
----
---- upper clad ^


---- fuel ^
---- lower clad ^
```

Then that pellet would be stacked, that stack has some above/below detail, then that block would be stacked again. 

I can see that given an individual `assemblies` input, you could totally get this level of detail, but the input would be pretty unreadable, whereas if I could repeat the initial pellet into a block, then that block into the full core, things could be much easier to input and read.

**Comment by youngmit** [comment]
The way that we typically approach repeated axial meshes is by linking the entire axial mesh. So in your case, something like:
```
assemblies:
    heights: &heights
        - 10
        - 10
        - 10
        - 10
        - 10
        - 10
    fuel:
        height: *heights
```

However, this doesnt really give you the flexibility to mix and match different zone meshes. I'm not sure if YAML has the ability to cobble together a sequence from a handful of anchors. What you've tried above is the best I have managed, and that is making a list of lists. I suppose we could consider implicitly flattening such a thing when processing blueprints, but I worry that that might end up becoming somewhat of a footgun.

Another option is to refine things with "axial mesh points" (see example here: https://github.com/terrapower/fftf-isothermal-model/blob/21a929a3f7d001f829bfea62fe1cb771b61363cb/FFTF-blueprints.yaml#L711). These are stored as a parameter on the blocks themselves, and it is rather up to the Interfaces to interpret them as they see fit. For instance, this is used as a hint when making the neutronics mesh of how to refine the grid. Note that this does not actually create more blocks, so things like block parameters are still stored on the mesh that is specified in "height".

Hope this helps.

**Comment by youngmit** [comment]
I also think it might be worth addressing your specific needs for how you are handling the fuel pellet that you mentioned. Given the brief description, I'm not sure exactly what you are trying to accomplish, but I'm assuming you have an assembly with an active fuel region and some plenum/structure above and below, where you want to mesh each axial region differently. In this case you can probably get away with a single fuel block blueprint, which has components for the fuel pellet(s), gap, cladding, etc. Then you would repeat that block as many times as needed into your assembly blueprint. Something like this, taken from the FFTF blueprints, slightly modified:
```
blocks:
  ...
  Inner Fuel Pin: &inner_fuel_pin
    fuel:
      ...
    gap:
      ...
    clad:
      ...
    wire:
      ...
    duct:
      ...
    intercoolant:
      ...
    coolant:
      ...

assemblies:
  heights: &heights

    - 9.144
    - 9.144
    - 9.144
    - 9.144
    - 4.572 # Finer mesh!
    - 4.572
    - 9.144
    - 9.144
    - 9.144
    - 9.144


  Inner Fuel:
    specifier: IC
    blocks:
    - *inner_fuel_pin
    - *inner_fuel_pin
    - *inner_fuel_pin
    - *inner_fuel_pin
    - *inner_fuel_pin
    - *inner_fuel_pin
    - *inner_fuel_pin
    - *inner_fuel_pin
    - *inner_fuel_pin
    - *inner_fuel_pin

    height: *heights
```

So in the above example the same block design is used in the coarse-axial mesh regions and fine-axial mesh region. The axial height of each block (and all of the components in it) are actually determined by the assembly that the blocks occupy. Notice that at least you can re-use the whole axial mesh in as many assembly designs as you want; this is pretty common approach.

Does this help?

**Comment by onufer** [comment]
Also, if you fuel components are more of 3D structure  (EG, torus, sphere, or cone) rather than a 2D structure extended along some axial range (eg cylinder, or extruded triangle/hexagon), we should probably discuss further to find the best approach.

**Comment by veeshy** [comment]
I don't think I got my idea across, sorry! I'll try again.

My unit cell I wish to repeat in the axial direction looks something like:
```
assemblies:
    fuel:
        blocks:
              - * unfueled_above_fuel_pellet_coating
              - * fuel_pellet
              - * unfueled_below_fuel_pellet_coating
        height:
              - 1
              - 3
              - 1
```

If I had 10 of these axially to represent one fuel stack, I would input 30 blocks/heights. Then If I had 10 fuel stacks, I would need to to have 300 blocks/heights. My case also happens to have some more axial detail between each of the fuel stacks.

interpreting via axial mesh seems okay, but I think I would move to a helper function to generate the blueprint before doing that since having arms blocks seems easier to my naive eyes.. 

Oh and a picture from MHTGR-350 benchmark, to perhaps help:

<img width="554" alt="image" src="https://user-images.githubusercontent.com/5826161/101546520-c08add80-395d-11eb-8c28-37010791c2e1.png">

Each of those blocks in the red region would have some axial granularity like locations where no fuel exists for fuel handling purposes
