### ISSUE TITLE
HTGR pin lattice not well mapped during vis-file

### ISSUE THREAD

**Issue by drewejohnson** [terrapower/armi#251]
I'm attempting to model an HTGR minicore and having a few issues / sticking points. The core is a simple 2-ring hex grid with a prismatic-like pin lattice
**Core**
![core-map](https://user-images.githubusercontent.com/19477741/108424956-ae93a980-71ee-11eb-8a9a-a48473b1a106.png)
**Pin lattice**
![pin-lattice](https://user-images.githubusercontent.com/19477741/108424957-ae93a980-71ee-11eb-890d-4c04470da455.png)

<details>
<summary>Blueprints.yaml</summary>

```yaml
blocks:
    fuel: &block_fuel
        grid name: pins
        duct: &comp_duct
            shape: Hexagon
            material: HT9
            Tinput: 600
            Thot: 600
            ip: 32
            op: 32.2
        fuel:
            shape: Circle
            material: UZr
            Tinput: 600
            Thot: 600
            id: 0.0
            od: 0.8
            latticeIDs: [FP]
        clad:
            shape: Circle
            material: Zr
            Tinput: 600
            Thot: 600
            id: fuel.od
            od: 0.9
            latticeIDs: [FP]
        pitch:
            shape: Hexagon
            material: Void
            Tinput: 600
            Thot: 600
            ip: 3
            op: 3
            latticeIDs: [FP, CL]
        cool pin:
            shape: Circle
            material: Graphite
            Tinput: 600
            Thot: 600
            id: 0
            od: fuel.od
            latticeIDs: [CL]
        coolant:
            shape: DerivedShape
            material: Graphite
            Tinput: 600
            Thot: 600
assemblies:
    heights: &heights
        - 50.0
    axial mesh points: &mesh
        - 2
    fuel:
        specifier : F
        blocks : &fuel_blocks
            - *block_fuel
        height: *heights
        axial mesh points: *mesh
        material modifications:
            U235_wt_frac:
                - 0.127
        xs types : &IC_xs
            - A
systems:
    core:
        grid name: core
        origin:
            x: 0.0
            y: 0.0
            z: 0.0
grids:
    !include minicore-coremap.yaml
```
</details>

<details>
<summary>Coremap.yaml</summary>

```yaml
core:
  geom: hex
  symmetry: full
  lattice map: |
    F
      F  F
    F
    F  F
      F
pins:
  geom: hex
  symmetry: full
  lattice map: |
    -   -   FP
      -   FP  FP
    -   CL  CL  CL
      FP  FP  FP  FP
    FP  FP  FP  FP  FP
      CL  CL  CL  CL
    FP  FP  FP  FP  FP
      FP  FP  FP  FP
    CL  CL  CL  CL  CL
      FP  FP  FP  FP
    FP  FP  FP  FP  FP
      CL  CL  CL  CL
    FP  FP  FP  FP  FP
      FP  FP  FP  FP
        CL  CL  CL
          FP  FP
            FP
```
</details>
ARMI 5b7d215 doesn't have any issue running the model and writing a datafile. The output of armi vis-file minicore.h5 yields

```
                       ---------------------------------------------------
                      |             _      ____     __  __    ___         |
                      |            / \    |  _ \   |  \/  |  |_ _|        |
                      |           / _ \   | |_) |  | |\/| |   | |         |
                      |          / ___ \  |  _ <   | |  | |   | |         |
                      |         /_/   \_\ |_| \_\  |_|  |_|  |___|        |
                      |         Advanced  Reactor  Modeling Interface     |
                       ---------------------------------------------------
                                      Version 0.1.6

[info] Creating visualization file for cycle 0, time node 0...
[info] Loading reactor state for time node (0, 0)
[info] Applying <Migration from 0.1.2: Removes now-invalid `centers:` lines fro...
[info] Removing `centers:` sections.
[info] Applying <Migration from 0.1.2: Update elemental nuclide flags....
=========== Initializing Mesh, Assembly Zones, and Nuclide Categories ===========
[info] Nuclide categorization for cross section temperature assignments:
       ------------------  -----------------------------------------------------------
       Nuclide Category    Nuclides
       ------------------  -----------------------------------------------------------
       Fuel                CM245, LFP41, PU236, PU241, DUMP1, ZR90, U238, ZR96, CM242,
                           PU238, U234, ZR91, PU239, U235, LFP35, AM242, AM243,
                           CM244, LFP40, NP238, ZR94, PU240, AM241, LFP38, NP237,
                           LFP39, ZR92, CM247, DUMP2, CM243, U236, PU242, CM246
       Coolant             C
       Structure           MO97, SI30, NI62, W183, NI58, FE56, MN55, CR52,
                           CR53, MO92, NI60, NI61, MO98, CR50, MO96,
                           SI28, SI29, FE58, NI64, V, W184, FE54,
                           MO100, CR54, MO95, W182, MO94, FE57, W186
       ------------------  -----------------------------------------------------------
[info] Assembly zone definitions:
       --------  ------  ------------  -----------------------------------------  ----------  ------
           Zone                                                                     Symmetry  Hot
         Number  Name      Assemblies  Locations                                      Factor  Zone
       --------  ------  ------------  -----------------------------------------  ----------  ------
              1  ring-1            31  A1001, A2001, A2002, A3001, A3002, A3003,           3  False
                                       A3012, A4001, A4002, A4003, A4004,
                                       A4005, A4018, A5001, A5002, A5003,
                                       A5004, A5005, A5006, A5023, A5024,
                                       A6001, A6002, A6003, A6004, A6005,
                                       A6006, A6007, A6008, A6029, A6030
       --------  ------  ------------  -----------------------------------------  ----------  ------
[info] The setting `splitZones` is enabled. Building subzones from core zones:
       --------  ------------------  ----------  ------------  -----------  ----------  ------
           Zone                      Original                                 Symmetry  Hot
         Number  Name                Name          Assemblies  Locations        Factor  Zone
       --------  ------------------  ----------  ------------  -----------  ----------  ------
              1  ring-1-reflector-1  ring-1                 1  A4005                 3  False
       --------  ------------------  ----------  ------------  -----------  ----------  ------
```
gives some spurious messages about the assemblies. I think this also causes the vtu file to not reflect the core geometry, or what I believe the core geometry should indicate
![paraview](https://user-images.githubusercontent.com/19477741/108426248-66758680-71f0-11eb-9eeb-4ae5a642b96a.png)

As a note, the current HEAD 1fd21f8236763f43c3bc25b866122aa9789486bc produces similar issues, but with different assembly naming
```
              1  ring-1            31  001-001, 002-001, 002-002, 003-001, 003-002, 003-003,           3  False
                                       003-012, 004-001, 004-002, 004-003, 004-004,
                                       004-005, 004-018, 005-001, 005-002, 005-003,
                                       005-004, 005-005, 005-006, 005-023, 005-024,
                                       006-001, 006-002, 006-003, 006-004, 006-005,
                                       006-006, 006-007, 006-008, 006-029, 006-030
```

I've thought about not using the `lattice map` for the pin grid and instead using `grid contents` which may let me specify the pin position with tuples (ring, pos) if I'm understanding the docs right - https://terrapower.github.io/armi/.apidocs/armi.reactor.blueprints.gridBlueprint.html#armi.reactor.blueprints.gridBlueprint.GridBlueprint.gridContents

As a consistency check, if you load this reactor up, the fuel lattice appears to be present in each block with the correct lattice structure. Checked based on the `spatialLocator` for circular components in a fuel block.
