### ISSUE TITLE
Finding hexagonal pin pitch for wire-less assemblies

### ISSUE THREAD

**Issue by drewejohnson** [terrapower/armi#252]
(Came up working on a custom plugin for the HTGR model in #251 but felt it merited a different discussion)

`HexBlock`s have a `getPinPitch` method which was my first guess for finding the pin pitch for a hexagonal pin lattice. But the [docs](https://terrapower.github.io/armi/.apidocs/armi.reactor.blocks.html#armi.reactor.blocks.HexBlock.getPinPitch) indicate that the pin pitch is defined by, and thus requires, wire and cladding. For an HTGR, where the fuel pellets might be placed in channels, these components might not exist in the reactor.

For a workaround, I found that adding a dummy component
```yaml
        pitch:
            shape: Hexagon
            material: Void
            Tinput: 600
            Thot: 600
            ip: 3
            op: 3
```
worked well. But this would imply that each block would require this component, even if the same underlying lattice map was used.

Could ARMI be extended to support a pitch attribute in the `lattice map` section for hexagonal lattices. The C5G7 example gives something like
```yaml
    UO2 grid:
        symmetry: full
        geom: cartesian
        lattice pitch:
            x: 1.26
            y: 1.26
```
