### ISSUE TITLE
Non-grid components have multiplicity of zero

### ISSUE THREAD

**Issue by drewejohnson** [terrapower/armi#254]
Using the inputs from #251, even if I force the multiplicity to be one with
```yaml
blocks:
    fuel: &block_fuel
        grid name: pins
        duct: &comp_duct
            shape: Hexagon
            material: HT9
            Tinput: 600
            Thot: 600
            ip: 32
            op: 32.2
            mult: 1
```
the duct still has no multiplicity
```python
import armi
from armi.reactor.flags import Flags
armi.configure()
o = armi.init(fName="minicore.yaml")
f = o.r.core.getFirstBlock(Flags.FUEL)
d = f.getComponentByName("duct")
d.getDimension("op")
32.2
d.getDimension("ip")
32.0
d.getDimension("mult")
0
d.getArea()
0.0
```
per https://github.com/terrapower/armi/blob/9e7c2984eae29ad0bb9752f9769cc17a7d12fec0/armi/reactor/components/basicShapes.py#L133-L138

This leads to problems when ARMI is computing volume fractions and can produce divide by zero errors in 
https://github.com/terrapower/armi/blob/9e7c2984eae29ad0bb9752f9769cc17a7d12fec0/armi/reactor/composites.py#L1544
