### ISSUE TITLE
Modeling ex-core structures: RPV, shielding, etc.

### ISSUE THREAD

**Issue by drewejohnson** [terrapower/armi#262]
Wanted to start a discussion / propose a new feature: ex-core structures in ARMI

The base system I'd like to model is one or more concentric right cylinders defining ex-core structures like core barrel, reactor pressure vessel (RPV) and shielding. I had a thought of adding some features to the blueprints file, like a block that doesn't make it's way into the core, but still utilizes material resolution and dimension linking. A new `ComplexShape` could be added to model the various aspects of the canning like
```yaml
excore:
    nshield:
        shape: RightCylinder
        id: 70
        od: 72
        bottomStart: 0
        bottomExtent: -5
        topStart: 100
        topExtent: 105
    RPV:
        shape: RightCylinder
        id: nshield.od
        od: 80
        bottomStart: nshield.bottomExtent
        bottomExtent: -20
        topStart: nshield.topExtent
        topExtent: 115
```
(dimensions made up) This information could be provided in the `blocks` section using circles rather than cylinders, and not placed in the core facemap. Maybe given a unique `Flag` to show it's part of the ex-core for bookkeeping and other checks, e.g., `getFirstBlock(Flags.EXCORE)`

I guess you could also model the upper / lower ex-core structures with dedicated axial layers. But you could run into a position like 
![rpv-gap](https://user-images.githubusercontent.com/19477741/109556761-13bb8a80-7a8c-11eb-9566-247cd577e60a.png)
where the vertical ex-core structures that make up the radial shielding don't form a connection with the two lowest levels. Or they would, but the green and blue materials don't line up correctly
![rpv-gap](https://user-images.githubusercontent.com/19477741/109556961-4feeeb00-7a8c-11eb-8543-0a1c7da426ba.png)

Another consideration would be "clipped" assemblies. In modeling the MHTGR in ARMI (#224), we'd likely have extra rings around the outside making up the "permanent reflector" which would then be clipped by the barrel to make up those complex outer shapes. 
![mhtgr](https://user-images.githubusercontent.com/19477741/109557154-904e6900-7a8c-11eb-9626-7afe130f41f3.png)

I've dropped a proxy barrel over the FFTF facemap as another example
![hex-with-intersecting-rpv](https://user-images.githubusercontent.com/19477741/109557252-b116be80-7a8c-11eb-991f-cec49c51e47d.png)
This will likely also have knock-on effects for tallying (full hex volume won't actually see neutrons) and visualization

The MHTGR also has some repeating arc-segments that make up coolant channels. The [BEAVRS](http://crpg.mit.edu/sites/default/files/css_injector_images_image/BEAVRS_2.0.2_spec.pdf) model has similar arcs for neutron shields between the core barrel and the RPV
![beavrs](https://user-images.githubusercontent.com/19477741/109557382-e4f1e400-7a8c-11eb-9753-90a6ca32f50d.png)
The region between the barrel, shield segments, and RPV could be filled with a `DerivedShape` to help model the down-comer region
