### ISSUE TITLE
Request: Multiple component links and arithmetic in blueprint files

### ISSUE THREAD

**Issue by keckler** [terrapower/armi#399]
In the blueprints files (specifically within the components section) we already have the ability to link component dimensions to each other. This is not only useful for avoiding repetition, but more importantly it is useful because it keeps the dimensions linked even through thermal expansion of the components.

However it seems that current capabilities only allow for linking a dimension through equality to a single other dimension (that has been defined previously) as in:

```
fuel:
    od: 0.5
clad:
    id: fuel.od
    od: 0.6
wire:
    helixDiameter: clad.od # there is only a single link here
```

What I would like to be possible is to have multiple existing dimensions combined through simple arithmetic as in:

```
fuel:
    od: 0.5
clad:
    id: fuel.od
    od: clad.id + 0.1 # there is some basic math here
wire:
    od: 0.01
    helixDiameter: clad.od + wire.od / 2 # there are two links here
```

I could possibly see some issues related to thermal expansion cropping up, but maybe those wouldn't be an issue assuming linear thermal expansion coefficients. 

This seems like a natural extension of the current linking capability, and I can think of more than one use case in a typical reactor problem.

Does anyone see any big issues here?
