### ISSUE TITLE
No warning when material modification is unused

### ISSUE THREAD

**Issue by keckler** [terrapower/armi#402]
Right now if you define an assembly with a material modification that is not recognized, ARMI does not tell you that it isn't recognized or that it is unused. For instance, I can define an assembly:

```yaml
assemblies:
  Testing123456:
    specifier: IC
    blocks:
    - name: DriverFuelBlock
      flags: FUEL
      fuel:
        shape: Circle
        material: UZr
        Tinput: 25.0
        Thot: 1500.0
        id: 0.0
        od: 0.5
        mult: 217
    height:
    - 666.0
    axial mesh points:
    - 666
    xs types:
    - B
    material modifications:
      this_is_a_fake_setting: # <--------------------------
        - 0.5
   ```

No mention of the modification `this_is_a_fake_setting` is made in the output. It would be useful for the user to know that their modifications are not recognized, at the very least as an input verification mechanism.
