### ISSUE TITLE
Grid Editor - Problem Saving Core Map

### ISSUE THREAD

**Issue by john-science** [terrapower/armi#490]
@jakehader Reported this bug: given the right conditions (which are common), the grid editor is failing to write output files.

## Steps to Reproduce the Bug

1. From the current "master" branch, open the grid editor on the command line: `$ armi grids`
2. Load this blueprints YAML file: [test-full-bp.zip](https://github.com/terrapower/armi/files/7598401/test-full-bp.zip)
3. Hit the buttons "Expand to full core" >> "Apply" >> "Save to grid blueprints..."
4. This will yield a valid output YAML file that looks like:

```yaml
core:
  geom: hex
  lattice map:
  grid bounds:
  symmetry: full
  grid contents:
    ? - 0
      - 0
    : IF
```
5. Now, add full ring of 6 "inner fuel"s around the central hex. and again "Save to grid blueprints..." You will now see the broken output YAML file:

```yaml
core:
  geom: hex
  lattice map: |-
    None
  grid bounds:
  symmetry: full
  grid contents:
```

## The Bug

The second core map above is wrong because it has no output data.

## What Caused this Bug?

Jake and determined this bug entered the "master" branch at this PR: https://github.com/terrapower/armi/pull/439
