### ISSUE TITLE
Request: `Holed` shapes with multiple hole sizes

### ISSUE THREAD

**Issue by keckler** [terrapower/armi#529]
Right now the [`HoledHexagon`](https://terrapower.github.io/armi/.apidocs/armi.reactor.components.complexShapes.html?highlight=holedhexagon#armi.reactor.components.complexShapes.HoledHexagon), [`HoledRectangle`](https://terrapower.github.io/armi/.apidocs/armi.reactor.components.complexShapes.html?highlight=holedhexagon#armi.reactor.components.complexShapes.HoledRectangle), and [`HoledSquare`](https://terrapower.github.io/armi/.apidocs/armi.reactor.components.complexShapes.html?highlight=holedhexagon#armi.reactor.components.complexShapes.HoledSquare) shapes are able to accept multiple holes, but all of the holes must be of the same dimension. I would like the ability to define these shapes with various (ideally arbitrary numbers of) hole sizes and to retain the ability to have arbitrary numbers of holes for a given size. This could be very useful for defining things like shield blocks or the assemblies of Sodium Graphite Reactors.

I looked into implementing this, but it seems like it would actually be somewhat difficult. My thought was an input that would look something like this:
```
blocks:
    block1:
        component1:
            shape: HoledHexagon
            material: SS316
            Tinput: 500
            Thot: 510
            op: 15
            holeOD: [0.1, 0.2, 0.3]
            nHoles: [4, 5, 6]
            mult: 1
        component2:
            shape: DerivedShape
            material: Sodium
            Tinput: 500
            Thot: 510
```
This would maintain backwards compatibility if the user didn't enter a list for the `holeOD` and `nHoles` attributes.

The issue is complicated by the current design of two major pieces (and possibly more):
1. The parsing of component attributes currently does not support values that are lists
2. The thermal expansion of components is not set up for an attribute that might be a list

Issue (1) can probably be relatively easily circumvented by modifying the [`from_yaml` within the `ComponentDimensions` class](https://terrapower.github.io/armi/.apidocs/armi.reactor.blueprints.componentBlueprint.html?highlight=componentdimension#armi.reactor.blueprints.componentBlueprint.ComponentDimension), if that were an acceptable solution.

But issue (2) seems quite a bit more complicated. In addition to lists not being supported right now from the perspective of expanding the dimensions, there is not currently a syntax in ARMI for linking dimensions that might be in a list. For instance, if we wanted to add a pin into one of the holes:
```

blocks:
    block1:
        component1:
            shape: HoledHexagon
            material: SS316
            Tinput: 500
            Thot: 510
            op: 15
            holeOD: [0.1, 0.2, 0.3]
            nHoles: [4, 5, 6]
            mult: 1
        component2:
            shape: Circle
            material: Inconel
            Tinput: 500
            Thot: 510
            od: component1.holeOD  # <------ How to specify which hole `od` is linked to?
            mult: 1
        component3:
            shape: DerivedShape
            material: Sodium
            Tinput: 500
            Thot: 510
```

I tried a couple things, but this is probably too much effort for me right now. If anyone else has any other ideas, I'd be happy to hear them.

**Comment by jakehader** [comment]
I think that generalizing these components to have "n" inputs will be generally challenging as you noted above. One problem as you noted is that the `setDimension` implementation of `Component` assumes that a single dimension name/key represents a single value (i.e., a float) and it does not know how to interpret a list of floats:

https://github.com/terrapower/armi/blob/9d1aaa76eadc0eb5c4f50cf8790d4fc2050e6322/armi/reactor/components/component.py#L723-L753

Another issue that you bring up is with component linking based on the name/key of the dimension. In this case we would need to be able to do something like `component1.holeOD.0` or something to represent linking to the value in the first index of the list. This would require some type of list expansion treatment at a pretty low level in the `Component` implementation.

My suggestion is that if you need up to "x" number of holes for your work that we consider a less elegant solution. For example, take "x" to be 3.

```
 blocks:
    block1:
        component1:
            shape: HoledHexagon
            material: SS316
            Tinput: 500
            Thot: 510
            op: 15
            holeOD: 0.1
            nHoles: 4
            holeOD2: 0.2
            nHoles2: 5
            holeOD3: 0.3
            nHoles3: 6
            mult: 1
        component2:
            shape: Circle
            material: Inconel
            Tinput: 500
            Thot: 510
            od: component1.holeOD
            mult: 1
        component3:
            shape: Circle
            material: Inconel
            Tinput: 500
            Thot: 510
            od: component1.holeOD2
            mult: 1
        component4:
            shape: DerivedShape
            material: Sodium
            Tinput: 500
            Thot: 510
```

This is not ideal because it doesn't offer a dynamic solution, but at a minimum it can extend the support of this complex block definition for your work while maintaining backwards compatibility. My guess is that many designs won't exceed 3 or 4 different hole types in practice, so this could at least be a stop gap until a generalized implementation is suggested.

Let's see what @john-science / @ntouran think about this.
